dbdata:
  image: busybox:latest
  volumes:
    - /var/lib/mysql

db:
  image: million12/mariadb:latest
  ports:
    - 3306
  volumes_from:
    - dbdata
  environment:
    - MARIADB_PASS=super-secret-db-password-123

webdata:
  image: busybox:latest
  volumes:
    - /data

web:
  image: million12/site-m12-io:latest
  hostname: dev.m12.io
  ports:
    - '8080:80'
  links:
    - db:db
  volumes_from:
    - webdata
  environment:
    - T3APP_NAME=m12
    - T3APP_VHOST_NAMES=dev.m12.io
    - T3APP_DB_NAME=neos_m12_io
    - T3APP_USER_NAME=admin
    - T3APP_USER_PASS=password
    - T3APP_USER_FNAME=M12
    - T3APP_USER_LNAME=IO
    - T3APP_NEOS_SITE_PACKAGE=M12.Site
    - T3APP_NEOS_SITE_PACKAGE_FORCE_REIMPORT=false
    - T3APP_ALWAYS_DO_PULL=false
    - SET_INTERNAL_PROXY_ON_PORT=3030
    - FLOW_CONTEXT=Development

ssh:
  image: million12/php-app-ssh
  ports:
    - '5678:22'
    - '3030:3030'
  links:
    - db:db
    - web:dev.m12.io
  volumes_from:
    - webdata
  environment:
    - IMPORT_GITHUB_PUB_KEYS=ryzy,sryzycki,pozgo
