dbdata:
  image: busybox:latest
  command: echo dbdata
  volumes:
    - /var/lib/mysql

db:
  image: million12/mariadb:latest
  ports:
    - 3306
  volumes_from:
    - dbdata
  environment:
    MARIADB_PASS: super-secret-db-password-123

webdata:
  image: busybox:latest
  command: echo webdata
  volumes:
    - /data

web:
  image: million12/site-m12-io:latest
  ports:
    - '8080:80'
  links:
    - db:db
  volumes_from:
    - webdata
  volumes:
    - /run/user/site-m12-io:/run/user
  environment:
    T3APP_NAME: 'm12'
    T3APP_VHOST_NAMES: 'm12.io dev.m12.io stage.m12.io test.m12.io'
    T3APP_DB_NAME: 't3n_m12_io'
    T3APP_USER_NAME: 'admin'
    T3APP_USER_PASS: 'password'
    T3APP_USER_FNAME: 'M12'
    T3APP_USER_LNAME: 'IO'
    T3APP_NEOS_SITE_PACKAGE: 'M12.Site'
    T3APP_NEOS_SITE_PACKAGE_FORCE_REIMPORT: false
    T3APP_ALWAYS_DO_PULL: false

ssh:
  image: million12/php-app-ssh
  ports:
    - '5678:22'
  links:
    - db:db
    - web:web
  volumes_from:
    - webdata
  environment:
    IMPORT_GITHUB_PUB_KEYS: ryzy
