
TYPO3:
  Flow:
    persistence:
      backendOptions:
        driver: pdo_mysql
        dbname: neos_m12_io
        user: admin
        password: super-secret-db-password-123
        host: db
        port: 3306

  Neos:
    userInterface:
      loadMinifiedJavascript: TRUE

#
# M12 blog settings
#
M12:
  Plugin:
    Blog:
      disqus:
        enabled: TRUE
        shortname: 'ryzycki-blog'
      feed:
        uri: '/blog.rss.xml'
        postsLimit: 20
        title: 'M12.io blog'
        description: 'MILLION12 DevOps and Neos CMS blog - m12.io'
        defaultAuthor: 'Marcin Ryzycki'
